version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis  # Adicione esta linha
      - gotenberg

  redis:  # Serviço do Redis
    image: redis:alpine
    ports:
      - "6379:6379"

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"