services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - gotenberg
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge